### ISSUE TITLE
guestip return nothing

### ISSUE THREAD

**Issue by harobed** [mkuzmin/vagrant-address#1]
My Vagrantfile :

```
Vagrant.configure("2") do |config|
    config.vm.box = "debian-jessie-amd64-netboot"
    config.vm.box_url = "https://github.com/holms/vagrant-jessie-box/releases/download/Jessie-v0.1/Debian-jessie-amd64-netboot.box"
    config.vm.hostname = "example"
    config.vm.network "private_network", type: "dhcp"
end
```

vagrant guestip output : 

```
$ vagrant  --version
Vagrant 1.7.2
$ vagrant guestip
```

**Comment by mkuzmin** [comment]
Current version of the plugin calls `ifconfig` inside the box to determine its address. Make sure it's available in $PATH.
In future I'll change this, and make it working the same way as `vagrant ssh`, but it requires preparing pull requests to Vagrant core.

**Comment by harobed** [comment]
Now I use this shell script

```
vagrant  ssh -- sudo ifconfig eth1 | awk '/inet addr/{print substr($2,6)}'
```

**Comment by mkuzmin** [comment]
You have to make ifconfig available without sudo. 
This is a requirement of Vagrant core, my plugin cannot control that.
