### ISSUE TITLE
Only returns address for eth0

### ISSUE THREAD

**Issue by joearcher** [mkuzmin/vagrant-address#2]
Great plugin, is there any way we can pass a parameter for the ethernet card we want the address for? We tend to use public networking on our Vagrant boxes and these addresses are assigned to eth1 by default, your plugin only returns the address for eth0.

**Comment by mkuzmin** [comment]
Yes, I've met the same issue already. 
In my last commit I've changed the logic, and future release will handle this situation correctly.
Unfortunately at the moment this new approach is supported by Hyper-V provider only. I still need to commit into Vagrant core to support VirtualBox provider.

**Comment by J0WI** [comment]
Any news on this?

**Comment by mkuzmin** [comment]
Vagrant authors rejected my pull request https://github.com/mitchellh/vagrant/pull/6574, but fixed related VirtualBox issue https://github.com/mitchellh/vagrant/issues/5978.
I will publish updated version after Vagrant 1.8 release.

**Comment by mkuzmin** [comment]
I've published a new version of the plugin under a new name: `vagrant-address`.
It fixes this issue, but has a VirtualBox compatibility problem: #5.
