### ISSUE TITLE
This command requires a specific VM name to target in a multi-VM environment.

### ISSUE THREAD

**Issue by l15k4** [mkuzmin/vagrant-address#3]
Hey,

I'm on ubuntu 14.04 `$ sudo apt-get install virtualbox vagrant`  and `Vagrant 1.7.4` and after I start vm with name `core-01` I get this error :

```
$ vagrant guestip
This command requires a specific VM name to target in a multi-VM environment.
$ vagrant guestip core-01
This command requires a specific VM name to target in a multi-VM environment.
```

I use default coreos Vagrant file...

**Comment by mkuzmin** [comment]
Could you share your `Vagrantfile` please

**Comment by l15k4** [comment]
I'm using this one : https://github.com/coreos/coreos-vagrant/blob/master/Vagrantfile

**Comment by mkuzmin** [comment]
I've published a new version of the plugin under a new name: `vagrant-address`.
It fixes this issue, but has a VirtualBox compatibility problem: #5.
