### ISSUE TITLE
In a docker environment, guestip returns docker's IP not guest's

### ISSUE THREAD

**Issue by syntacticvexation** [mkuzmin/vagrant-address#4]
Hi,

See above.  As docker0 is the first interface that is returned by ifconfig, this IP is returned and not eth0 or eth1.

Cheers.

**Comment by mkuzmin** [comment]
Yeah, I've met this issue too. There is pre-release version `0.3.pre1` published, where this issue is fixed, 

But it's not compatible with VirtualBox provider. We have to wait until https://github.com/mitchellh/vagrant/issues/5978 is fixed.

**Comment by mkuzmin** [comment]
I've published a new version of the plugin under a new name: `vagrant-address`.
It fixes this issue, but has a VirtualBox compatibility problem: #5.

**Comment by syntacticvexation** [comment]
Thanks.  I've tested it, I now get a helpful error message. :)

**Comment by mkuzmin** [comment]
I hope this will be fixed in Vagrant 1.8.1
