### ISSUE TITLE
On OpenStack I cant get the address

### ISSUE THREAD

**Issue by jellyDean** [mkuzmin/vagrant-address#6]
The capability 'public_address' could not be found. This is an internal error
that users should never see. Please report a bug.

**Comment by mkuzmin** [comment]
Which Vagrant version do you use?
Can you `vagrant ssh` into this machine successfully?

Please provide a debug log using `vagrant address --debug` (better with a [gist](https://gist.github.com/)).

**Comment by jellyDean** [comment]
i was using 1.7.4 and was able to ssh into the machine. I upgraded vagrant to 1.8.1 and now have a new issue:


> dean.hutton@Bhtechs-Mac-mini ~/G/salt-vagrant-demo> vagrant address master
/Users/dean.hutton/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:13:in `require': incompatible library version - /Users/dean.hutton/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext/parser.bundle (fatal)
	from /Users/dean.hutton/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:13:in `<module:Ext>'
	from /Users/dean.hutton/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:12:in `<module:JSON>'
	from /Users/dean.hutton/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:9:in `<top (required)>'
	from /Users/dean.hutton/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:58:in `require'
	from /Users/dean.hutton/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:58:in `<module:JSON>'
	from /Users/dean.hutton/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:54:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:55:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:55:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `<main>'

>

**Comment by jellyDean** [comment]
Currently using 1.7.4 with OpenStack as my provider and I am able to ssh into the machine.

Here is the gist: https://gist.github.com/jellyDean/cf1584db0124613bf1ac

**Comment by mkuzmin** [comment]
Hi

This issue happens because `vagrant-openstack-provider` does not implement required API.
I've reported the issue to them: https://github.com/ggiamarchi/vagrant-openstack-provider/issues/276

At my side I will try to provide better error messages in such cases: https://github.com/mkuzmin/vagrant-address/issues/7
