### ISSUE TITLE
How to use this thanks

### ISSUE THREAD

**Issue by scheung38** [mkuzmin/vagrant-address#8]
vagrant address [???]

How do you find the name of the vagrant instance?

$ vagrant address precise64
The machine with the name 'precise64' was not found configured for
this Vagrant environment.

$ vagrant address vagrant@precise64
The machine with the name 'vagrant@precise64' was not found configured for
this Vagrant environment.

**Comment by savishy** [comment]
It's `vagrant address <machine name>` where `machine name` is the name of your machine as listed in `vagrant status`.
Obviously you would need to execute the command where your `Vagrantfile` is.

**Comment by mkuzmin** [comment]
Yes, you need `Vagrantfile` created in advance.

`<machine name>` argument is required in [multi-machine environments](https://www.vagrantup.com/docs/multi-machine/) only.
